#! /bin/sh
### BEGIN INIT INFO
# Provides:          do-nsupdate
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Author: Armen Baghumian <armen@OpenSourceClub.org>
#
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="do-nsupdate"
NAME="do-nsupdate.sh"
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
DAEMON_USER=root

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        if [ -e $PIDFILE ]
        then
            echo
            echo "Error: $PIDFILE already exists."
            echo "Cannot start $NAME more than once."
            echo
        else
            log_daemon_msg "Starting $DESC" "$NAME"
            echo
            /sbin/start-stop-daemon --start --quiet --background \
                --chuid $DAEMON_USER --make-pidfile \
                --pidfile $PIDFILE --exec $DAEMON -- "$DAEMON_ARGS"
        fi
	;;
    stop)
        if [ -e $PIDFILE ]
        then
            log_daemon_msg "Stoping $DESC" "$NAME"
            echo
            /sbin/start-stop-daemon --stop --pidfile $PIDFILE
            rm -f $PIDFILE
        else
            echo
            echo "Error: $PIDFILE not found."
            echo "Could not stop $NAME."
            echo
        fi
	;;
    *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac
